server:
  port: 7000
spring:
  application:
    name: Spring-Boot-Mail-App
  mail:
    # SMTP服务主机地址
#    host:
#    username:
#    password:
    port: 25
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
