server:
  port: 7000

spring:
  application:
    name: nacos-provider-app
  cloud:
    nacos:
      discovery:
        # 是否开启Nacos的服务发现功能
        enabled: true
        # 是否将当前服务注册到Nacos中，true表示确定注册
        register-enabled: true
        # Nacos服务地址
        server-addr: 192.168.29.130:8848